# Generated by Django 3.0.8 on 2020-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200731_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=1, upload_to='profile_picture/'),
            preserve_default=False,
        ),
    ]
