# Generated by Django 3.0.8 on 2020-07-27 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0002_auto_20200726_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 10, 44, 16, 609013, tzinfo=utc)),
        ),
    ]
