# Generated by Django 3.0.8 on 2020-07-27 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0003_auto_20200727_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 11, 37, 46, 671128, tzinfo=utc)),
        ),
    ]
