# Generated by Django 3.0.8 on 2020-07-28 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0006_auto_20200728_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 14, 36, 46, 332927, tzinfo=utc)),
        ),
    ]
