# Generated by Django 3.0.8 on 2020-07-30 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0007_auto_20200728_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 15, 53, 4, 959695, tzinfo=utc)),
        ),
    ]
