# Generated by Django 3.0.8 on 2020-07-30 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0008_auto_20200730_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 16, 35, 20, 432228, tzinfo=utc)),
        ),
    ]
