# Generated by Django 3.0.8 on 2020-08-01 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0012_auto_20200801_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 1, 13, 16, 26, 349438, tzinfo=utc)),
        ),
    ]
