# Generated by Django 3.0.8 on 2020-08-01 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_auto_20200726_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='childrens',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(default='A beautiful place', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=11),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=5),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=11),
        ),
        migrations.AlterField(
            model_name='roomstype',
            name='bathroom_type',
            field=models.CharField(choices=[('Communal', 'Communal'), ('Private', 'Private')], max_length=8),
        ),
        migrations.AlterField(
            model_name='roomstype',
            name='bed_type',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Queen', 'Queen'), ('King', 'King')], max_length=6),
        ),
    ]
